/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addressesGet } from "../funcs/addressesGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Addresses extends ClientSDK {
  async get(
    request: operations.AddressesGetRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesGetResponseBody> {
    return unwrapAsync(addressesGet(
      this,
      request,
      options,
    ));
  }
}
