/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { addressesCreate } from "../funcs/addressesCreate.js";
import { addressesGet } from "../funcs/addressesGet.js";
import { addressesList } from "../funcs/addressesList.js";
import { addressesUpdate } from "../funcs/addressesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Addresses extends ClientSDK {
  async list(
    request: operations.AddressesListRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.AddressesListResponseBody>> {
    return unwrapAsync(addressesList(
      this,
      request,
      options,
    ));
  }

  async create(
    request: operations.AddressesCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesCreateResponseBody> {
    return unwrapAsync(addressesCreate(
      this,
      request,
      options,
    ));
  }

  async get(
    request: operations.AddressesGetRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesGetResponseBody> {
    return unwrapAsync(addressesGet(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.AddressesUpdateRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesUpdateResponseBody> {
    return unwrapAsync(addressesUpdate(
      this,
      request,
      options,
    ));
  }
}
