/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { developerToolsCreateApiKey } from "../funcs/developerToolsCreateApiKey.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class DeveloperTools extends ClientSDK {
  async createApiKey(
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(developerToolsCreateApiKey(
      this,
      options,
    ));
  }
}
