/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersAddressesCreate } from "../funcs/customersAddressesCreate.js";
import { customersAddressesUpdate } from "../funcs/customersAddressesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class JaniPaymentsAddresses extends ClientSDK {
  async create(
    request: operations.AddressesCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesCreateResponseBody> {
    return unwrapAsync(customersAddressesCreate(
      this,
      request,
      options,
    ));
  }

  async update(
    request: operations.AddressesUpdateRequest,
    options?: RequestOptions,
  ): Promise<operations.AddressesUpdateResponseBody> {
    return unwrapAsync(customersAddressesUpdate(
      this,
      request,
      options,
    ));
  }
}
