/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionPause } from "../funcs/subscriptionPause.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Subscription extends ClientSDK {
  async pause(
    request: operations.SubscriptionPauseSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<operations.SubscriptionPauseSubscriptionResponseBody> {
    return unwrapAsync(subscriptionPause(
      this,
      request,
      options,
    ));
  }
}
