workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    JaniPayments-OAS:
        inputs:
            - location: https://billing.jani-ai.com/doc
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/jani-payments/billing/jani-payments-oas
targets:
    jani-payments:
        target: typescript
        source: JaniPayments-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/jani-payments/billing/jani-payments-oas-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
