/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Any valid JSON value
 */
export type AddressesUpdateCustomData = {};

export const AddressesUpdateStatus = {
  Active: "active",
  Archived: "archived",
} as const;
export type AddressesUpdateStatus = ClosedEnum<typeof AddressesUpdateStatus>;

export type AddressesUpdateRequestBody = {
  description?: string | null | undefined;
  firstLine?: string | null | undefined;
  /**
   * Any valid JSON value
   */
  customData?: AddressesUpdateCustomData | undefined;
  city?: string | null | undefined;
  status?: AddressesUpdateStatus | undefined;
  customerId?: string | null | undefined;
};

export type AddressesUpdateRequest = {
  customerId: string;
  addressId: string;
  /**
   * organization_Id
   */
  organizationId: string;
  requestBody: AddressesUpdateRequestBody;
};

/**
 * Any valid JSON value
 */
export type AddressesUpdateAddressesCustomData = {};

export const AddressesUpdateAddressesStatus = {
  Active: "active",
  Archived: "archived",
} as const;
export type AddressesUpdateAddressesStatus = ClosedEnum<
  typeof AddressesUpdateAddressesStatus
>;

/**
 * Update an Address
 */
export type AddressesUpdateResponseBody = {
  id: string;
  description?: string | null | undefined;
  firstLine?: string | null | undefined;
  /**
   * Any valid JSON value
   */
  customData: AddressesUpdateAddressesCustomData;
  city?: string | null | undefined;
  status: AddressesUpdateAddressesStatus;
  createdAt: string;
  updatedAt: string;
  customerId?: string | null | undefined;
};

/** @internal */
export const AddressesUpdateCustomData$inboundSchema: z.ZodType<
  AddressesUpdateCustomData,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type AddressesUpdateCustomData$Outbound = {};

/** @internal */
export const AddressesUpdateCustomData$outboundSchema: z.ZodType<
  AddressesUpdateCustomData$Outbound,
  z.ZodTypeDef,
  AddressesUpdateCustomData
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressesUpdateCustomData$ {
  /** @deprecated use `AddressesUpdateCustomData$inboundSchema` instead. */
  export const inboundSchema = AddressesUpdateCustomData$inboundSchema;
  /** @deprecated use `AddressesUpdateCustomData$outboundSchema` instead. */
  export const outboundSchema = AddressesUpdateCustomData$outboundSchema;
  /** @deprecated use `AddressesUpdateCustomData$Outbound` instead. */
  export type Outbound = AddressesUpdateCustomData$Outbound;
}

export function addressesUpdateCustomDataToJSON(
  addressesUpdateCustomData: AddressesUpdateCustomData,
): string {
  return JSON.stringify(
    AddressesUpdateCustomData$outboundSchema.parse(addressesUpdateCustomData),
  );
}

export function addressesUpdateCustomDataFromJSON(
  jsonString: string,
): SafeParseResult<AddressesUpdateCustomData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddressesUpdateCustomData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddressesUpdateCustomData' from JSON`,
  );
}

/** @internal */
export const AddressesUpdateStatus$inboundSchema: z.ZodNativeEnum<
  typeof AddressesUpdateStatus
> = z.nativeEnum(AddressesUpdateStatus);

/** @internal */
export const AddressesUpdateStatus$outboundSchema: z.ZodNativeEnum<
  typeof AddressesUpdateStatus
> = AddressesUpdateStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressesUpdateStatus$ {
  /** @deprecated use `AddressesUpdateStatus$inboundSchema` instead. */
  export const inboundSchema = AddressesUpdateStatus$inboundSchema;
  /** @deprecated use `AddressesUpdateStatus$outboundSchema` instead. */
  export const outboundSchema = AddressesUpdateStatus$outboundSchema;
}

/** @internal */
export const AddressesUpdateRequestBody$inboundSchema: z.ZodType<
  AddressesUpdateRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.nullable(z.string()).optional(),
  first_line: z.nullable(z.string()).optional(),
  custom_data: z.lazy(() => AddressesUpdateCustomData$inboundSchema).optional(),
  city: z.nullable(z.string()).optional(),
  status: AddressesUpdateStatus$inboundSchema.optional(),
  customer_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "first_line": "firstLine",
    "custom_data": "customData",
    "customer_id": "customerId",
  });
});

/** @internal */
export type AddressesUpdateRequestBody$Outbound = {
  description?: string | null | undefined;
  first_line?: string | null | undefined;
  custom_data?: AddressesUpdateCustomData$Outbound | undefined;
  city?: string | null | undefined;
  status?: string | undefined;
  customer_id?: string | null | undefined;
};

/** @internal */
export const AddressesUpdateRequestBody$outboundSchema: z.ZodType<
  AddressesUpdateRequestBody$Outbound,
  z.ZodTypeDef,
  AddressesUpdateRequestBody
> = z.object({
  description: z.nullable(z.string()).optional(),
  firstLine: z.nullable(z.string()).optional(),
  customData: z.lazy(() => AddressesUpdateCustomData$outboundSchema).optional(),
  city: z.nullable(z.string()).optional(),
  status: AddressesUpdateStatus$outboundSchema.optional(),
  customerId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    firstLine: "first_line",
    customData: "custom_data",
    customerId: "customer_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressesUpdateRequestBody$ {
  /** @deprecated use `AddressesUpdateRequestBody$inboundSchema` instead. */
  export const inboundSchema = AddressesUpdateRequestBody$inboundSchema;
  /** @deprecated use `AddressesUpdateRequestBody$outboundSchema` instead. */
  export const outboundSchema = AddressesUpdateRequestBody$outboundSchema;
  /** @deprecated use `AddressesUpdateRequestBody$Outbound` instead. */
  export type Outbound = AddressesUpdateRequestBody$Outbound;
}

export function addressesUpdateRequestBodyToJSON(
  addressesUpdateRequestBody: AddressesUpdateRequestBody,
): string {
  return JSON.stringify(
    AddressesUpdateRequestBody$outboundSchema.parse(addressesUpdateRequestBody),
  );
}

export function addressesUpdateRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<AddressesUpdateRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddressesUpdateRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddressesUpdateRequestBody' from JSON`,
  );
}

/** @internal */
export const AddressesUpdateRequest$inboundSchema: z.ZodType<
  AddressesUpdateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_id: z.string(),
  address_id: z.string(),
  organization_Id: z.string(),
  RequestBody: z.lazy(() => AddressesUpdateRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "address_id": "addressId",
    "organization_Id": "organizationId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type AddressesUpdateRequest$Outbound = {
  customer_id: string;
  address_id: string;
  organization_Id: string;
  RequestBody: AddressesUpdateRequestBody$Outbound;
};

/** @internal */
export const AddressesUpdateRequest$outboundSchema: z.ZodType<
  AddressesUpdateRequest$Outbound,
  z.ZodTypeDef,
  AddressesUpdateRequest
> = z.object({
  customerId: z.string(),
  addressId: z.string(),
  organizationId: z.string(),
  requestBody: z.lazy(() => AddressesUpdateRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    addressId: "address_id",
    organizationId: "organization_Id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressesUpdateRequest$ {
  /** @deprecated use `AddressesUpdateRequest$inboundSchema` instead. */
  export const inboundSchema = AddressesUpdateRequest$inboundSchema;
  /** @deprecated use `AddressesUpdateRequest$outboundSchema` instead. */
  export const outboundSchema = AddressesUpdateRequest$outboundSchema;
  /** @deprecated use `AddressesUpdateRequest$Outbound` instead. */
  export type Outbound = AddressesUpdateRequest$Outbound;
}

export function addressesUpdateRequestToJSON(
  addressesUpdateRequest: AddressesUpdateRequest,
): string {
  return JSON.stringify(
    AddressesUpdateRequest$outboundSchema.parse(addressesUpdateRequest),
  );
}

export function addressesUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<AddressesUpdateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddressesUpdateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddressesUpdateRequest' from JSON`,
  );
}

/** @internal */
export const AddressesUpdateAddressesCustomData$inboundSchema: z.ZodType<
  AddressesUpdateAddressesCustomData,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type AddressesUpdateAddressesCustomData$Outbound = {};

/** @internal */
export const AddressesUpdateAddressesCustomData$outboundSchema: z.ZodType<
  AddressesUpdateAddressesCustomData$Outbound,
  z.ZodTypeDef,
  AddressesUpdateAddressesCustomData
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressesUpdateAddressesCustomData$ {
  /** @deprecated use `AddressesUpdateAddressesCustomData$inboundSchema` instead. */
  export const inboundSchema = AddressesUpdateAddressesCustomData$inboundSchema;
  /** @deprecated use `AddressesUpdateAddressesCustomData$outboundSchema` instead. */
  export const outboundSchema =
    AddressesUpdateAddressesCustomData$outboundSchema;
  /** @deprecated use `AddressesUpdateAddressesCustomData$Outbound` instead. */
  export type Outbound = AddressesUpdateAddressesCustomData$Outbound;
}

export function addressesUpdateAddressesCustomDataToJSON(
  addressesUpdateAddressesCustomData: AddressesUpdateAddressesCustomData,
): string {
  return JSON.stringify(
    AddressesUpdateAddressesCustomData$outboundSchema.parse(
      addressesUpdateAddressesCustomData,
    ),
  );
}

export function addressesUpdateAddressesCustomDataFromJSON(
  jsonString: string,
): SafeParseResult<AddressesUpdateAddressesCustomData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AddressesUpdateAddressesCustomData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddressesUpdateAddressesCustomData' from JSON`,
  );
}

/** @internal */
export const AddressesUpdateAddressesStatus$inboundSchema: z.ZodNativeEnum<
  typeof AddressesUpdateAddressesStatus
> = z.nativeEnum(AddressesUpdateAddressesStatus);

/** @internal */
export const AddressesUpdateAddressesStatus$outboundSchema: z.ZodNativeEnum<
  typeof AddressesUpdateAddressesStatus
> = AddressesUpdateAddressesStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressesUpdateAddressesStatus$ {
  /** @deprecated use `AddressesUpdateAddressesStatus$inboundSchema` instead. */
  export const inboundSchema = AddressesUpdateAddressesStatus$inboundSchema;
  /** @deprecated use `AddressesUpdateAddressesStatus$outboundSchema` instead. */
  export const outboundSchema = AddressesUpdateAddressesStatus$outboundSchema;
}

/** @internal */
export const AddressesUpdateResponseBody$inboundSchema: z.ZodType<
  AddressesUpdateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  description: z.nullable(z.string()).optional(),
  first_line: z.nullable(z.string()).optional(),
  custom_data: z.lazy(() => AddressesUpdateAddressesCustomData$inboundSchema),
  city: z.nullable(z.string()).optional(),
  status: AddressesUpdateAddressesStatus$inboundSchema,
  created_at: z.string(),
  updated_at: z.string(),
  customer_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "first_line": "firstLine",
    "custom_data": "customData",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "customer_id": "customerId",
  });
});

/** @internal */
export type AddressesUpdateResponseBody$Outbound = {
  id: string;
  description?: string | null | undefined;
  first_line?: string | null | undefined;
  custom_data: AddressesUpdateAddressesCustomData$Outbound;
  city?: string | null | undefined;
  status: string;
  created_at: string;
  updated_at: string;
  customer_id?: string | null | undefined;
};

/** @internal */
export const AddressesUpdateResponseBody$outboundSchema: z.ZodType<
  AddressesUpdateResponseBody$Outbound,
  z.ZodTypeDef,
  AddressesUpdateResponseBody
> = z.object({
  id: z.string(),
  description: z.nullable(z.string()).optional(),
  firstLine: z.nullable(z.string()).optional(),
  customData: z.lazy(() => AddressesUpdateAddressesCustomData$outboundSchema),
  city: z.nullable(z.string()).optional(),
  status: AddressesUpdateAddressesStatus$outboundSchema,
  createdAt: z.string(),
  updatedAt: z.string(),
  customerId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    firstLine: "first_line",
    customData: "custom_data",
    createdAt: "created_at",
    updatedAt: "updated_at",
    customerId: "customer_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddressesUpdateResponseBody$ {
  /** @deprecated use `AddressesUpdateResponseBody$inboundSchema` instead. */
  export const inboundSchema = AddressesUpdateResponseBody$inboundSchema;
  /** @deprecated use `AddressesUpdateResponseBody$outboundSchema` instead. */
  export const outboundSchema = AddressesUpdateResponseBody$outboundSchema;
  /** @deprecated use `AddressesUpdateResponseBody$Outbound` instead. */
  export type Outbound = AddressesUpdateResponseBody$Outbound;
}

export function addressesUpdateResponseBodyToJSON(
  addressesUpdateResponseBody: AddressesUpdateResponseBody,
): string {
  return JSON.stringify(
    AddressesUpdateResponseBody$outboundSchema.parse(
      addressesUpdateResponseBody,
    ),
  );
}

export function addressesUpdateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AddressesUpdateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddressesUpdateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddressesUpdateResponseBody' from JSON`,
  );
}
